# Generated by Django 3.0.8 on 2020-09-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_web", "0002_auto_20200901_1232"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="name",
            field=models.CharField(blank=True, max_length=100, verbose_name="country"),
        ),
    ]
