# Generated by Django 3.0.8 on 2020-07-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_web', '0003_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
