# Generated by Django 3.0.8 on 2020-07-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_web', '0005_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/images/default.jpg', upload_to='images', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='file'),
        ),
    ]
