# Generated by Django 3.0.8 on 2020-09-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_web', '0005_auto_20200903_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='saved_for_later',
            field=models.BooleanField(default=False, verbose_name='saved_for_later'),
        ),
    ]
