# Generated by Django 3.0.8 on 2020-09-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_web', '0008_auto_20200903_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='amount'),
        ),
    ]
