# Generated by Django 3.0.8 on 2020-09-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_web', '0009_auto_20200903_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(default='pending', max_length=100, verbose_name='status'),
        ),
    ]
