# Generated by Django 3.0.8 on 2020-09-04 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store_web", "0010_auto_20200903_1451"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders",
            old_name="user",
            new_name="users",
        ),
    ]
