# Generated by Django 3.0.8 on 2020-09-18 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store_web", "0015_auto_20200917_1324"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="users",
        ),
        migrations.AddField(
            model_name="orders",
            name="users",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
