# Generated by Django 3.0.8 on 2020-09-18 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store_web", "0017_auto_20200918_1803"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="addresses",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store_web.Address"
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="users",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
