# Generated by Django 3.1.1 on 2020-10-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_web', '0020_auto_20200922_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='https://store-static-files.s3.amazonaws.com/media/media/images/default.jpg', upload_to='images', verbose_name='image'),
        ),
    ]
